export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const FILTER_BY_CREATE = 'FILTER_BY_CREATE';
export const ORDER_BY_NAME= 'ORDER_BY_NAME';
export const ORDER_BY_RATING= 'ORDER_BY_RATING';
export const FILTER_BY_NAME = 'FILTER_BY_NAME';
export const FILTER_BY_GENRE = 'FILTER_BY_GENRE';
export const GET_DETAIL = 'GET_DETAIL';
export const POST_VIDEOGAME = 'POST_VIDEOGAME';
export const GET_GENRES = 'GET_GENRES'; 

